// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminpermission"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdminPermissionUpdate is the builder for updating AdminPermission entities.
type AdminPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *AdminPermissionMutation
}

// Where appends a list predicates to the AdminPermissionUpdate builder.
func (_u *AdminPermissionUpdate) Where(ps ...predicate.AdminPermission) *AdminPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminPermissionUpdate) SetUpdatedAt(v time.Time) *AdminPermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AdminPermissionUpdate) SetUserID(v int64) *AdminPermissionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableUserID(v *int64) *AdminPermissionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *AdminPermissionUpdate) SetResource(v string) *AdminPermissionUpdate {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableResource(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetActions sets the "actions" field.
func (_u *AdminPermissionUpdate) SetActions(v []string) *AdminPermissionUpdate {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *AdminPermissionUpdate) AppendActions(v []string) *AdminPermissionUpdate {
	_u.mutation.AppendActions(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AdminPermissionUpdate) SetUser(v *User) *AdminPermissionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AdminPermissionMutation object of the builder.
func (_u *AdminPermissionUpdate) Mutation() *AdminPermissionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AdminPermissionUpdate) ClearUser() *AdminPermissionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminPermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminPermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminPermissionUpdate) check() error {
	if v, ok := _u.mutation.Resource(); ok {
		if err := adminpermission.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.resource": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminPermission.user"`)
	}
	return nil
}

func (_u *AdminPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminpermission.Table, adminpermission.Columns, sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(adminpermission.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(adminpermission.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, adminpermission.FieldActions, value)
		})
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminpermission.UserTable,
			Columns: []string{adminpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminpermission.UserTable,
			Columns: []string{adminpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminPermissionUpdateOne is the builder for updating a single AdminPermission entity.
type AdminPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminPermissionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminPermissionUpdateOne) SetUpdatedAt(v time.Time) *AdminPermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AdminPermissionUpdateOne) SetUserID(v int64) *AdminPermissionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableUserID(v *int64) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *AdminPermissionUpdateOne) SetResource(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableResource(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetActions sets the "actions" field.
func (_u *AdminPermissionUpdateOne) SetActions(v []string) *AdminPermissionUpdateOne {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *AdminPermissionUpdateOne) AppendActions(v []string) *AdminPermissionUpdateOne {
	_u.mutation.AppendActions(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AdminPermissionUpdateOne) SetUser(v *User) *AdminPermissionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AdminPermissionMutation object of the builder.
func (_u *AdminPermissionUpdateOne) Mutation() *AdminPermissionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AdminPermissionUpdateOne) ClearUser() *AdminPermissionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AdminPermissionUpdate builder.
func (_u *AdminPermissionUpdateOne) Where(ps ...predicate.AdminPermission) *AdminPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminPermissionUpdateOne) Select(field string, fields ...string) *AdminPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminPermission entity.
func (_u *AdminPermissionUpdateOne) Save(ctx context.Context) (*AdminPermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminPermissionUpdateOne) SaveX(ctx context.Context) *AdminPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminPermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.Resource(); ok {
		if err := adminpermission.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.resource": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminPermission.user"`)
	}
	return nil
}

func (_u *AdminPermissionUpdateOne) sqlSave(ctx context.Context) (_node *AdminPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminpermission.Table, adminpermission.Columns, sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminpermission.FieldID)
		for _, f := range fields {
			if !adminpermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminpermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(adminpermission.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(adminpermission.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, adminpermission.FieldActions, value)
		})
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminpermission.UserTable,
			Columns: []string{adminpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminpermission.UserTable,
			Columns: []string{adminpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdminPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
