// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminpermission"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdminPermissionCreate is the builder for creating a AdminPermission entity.
type AdminPermissionCreate struct {
	config
	mutation *AdminPermissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminPermissionCreate) SetCreatedAt(v time.Time) *AdminPermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminPermissionCreate) SetNillableCreatedAt(v *time.Time) *AdminPermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdminPermissionCreate) SetUpdatedAt(v time.Time) *AdminPermissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdminPermissionCreate) SetNillableUpdatedAt(v *time.Time) *AdminPermissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AdminPermissionCreate) SetUserID(v int64) *AdminPermissionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetResource sets the "resource" field.
func (_c *AdminPermissionCreate) SetResource(v string) *AdminPermissionCreate {
	_c.mutation.SetResource(v)
	return _c
}

// SetActions sets the "actions" field.
func (_c *AdminPermissionCreate) SetActions(v []string) *AdminPermissionCreate {
	_c.mutation.SetActions(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AdminPermissionCreate) SetUser(v *User) *AdminPermissionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AdminPermissionMutation object of the builder.
func (_c *AdminPermissionCreate) Mutation() *AdminPermissionMutation {
	return _c.mutation
}

// Save creates the AdminPermission in the database.
func (_c *AdminPermissionCreate) Save(ctx context.Context) (*AdminPermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminPermissionCreate) SaveX(ctx context.Context) *AdminPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminPermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminPermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminPermissionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminpermission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := adminpermission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminPermissionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminPermission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminPermission.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AdminPermission.user_id"`)}
	}
	if _, ok := _c.mutation.Resource(); !ok {
		return &ValidationError{Name: "resource", err: errors.New(`ent: missing required field "AdminPermission.resource"`)}
	}
	if v, ok := _c.mutation.Resource(); ok {
		if err := adminpermission.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.resource": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Actions(); !ok {
		return &ValidationError{Name: "actions", err: errors.New(`ent: missing required field "AdminPermission.actions"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AdminPermission.user"`)}
	}
	return nil
}

func (_c *AdminPermissionCreate) sqlSave(ctx context.Context) (*AdminPermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminPermissionCreate) createSpec() (*AdminPermission, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminPermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminpermission.Table, sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminpermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adminpermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Resource(); ok {
		_spec.SetField(adminpermission.FieldResource, field.TypeString, value)
		_node.Resource = value
	}
	if value, ok := _c.mutation.Actions(); ok {
		_spec.SetField(adminpermission.FieldActions, field.TypeJSON, value)
		_node.Actions = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminpermission.UserTable,
			Columns: []string{adminpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminPermission.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminPermissionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminPermissionCreate) OnConflict(opts ...sql.ConflictOption) *AdminPermissionUpsertOne {
	_c.conflict = opts
	return &AdminPermissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminPermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminPermissionCreate) OnConflictColumns(columns ...string) *AdminPermissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminPermissionUpsertOne{
		create: _c,
	}
}

type (
	// AdminPermissionUpsertOne is the builder for "upsert"-ing
	//  one AdminPermission node.
	AdminPermissionUpsertOne struct {
		create *AdminPermissionCreate
	}

	// AdminPermissionUpsert is the "OnConflict" setter.
	AdminPermissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AdminPermissionUpsert) SetUpdatedAt(v time.Time) *AdminPermissionUpsert {
	u.Set(adminpermission.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdminPermissionUpsert) UpdateUpdatedAt() *AdminPermissionUpsert {
	u.SetExcluded(adminpermission.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AdminPermissionUpsert) SetUserID(v int64) *AdminPermissionUpsert {
	u.Set(adminpermission.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminPermissionUpsert) UpdateUserID() *AdminPermissionUpsert {
	u.SetExcluded(adminpermission.FieldUserID)
	return u
}

// SetResource sets the "resource" field.
func (u *AdminPermissionUpsert) SetResource(v string) *AdminPermissionUpsert {
	u.Set(adminpermission.FieldResource, v)
	return u
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *AdminPermissionUpsert) UpdateResource() *AdminPermissionUpsert {
	u.SetExcluded(adminpermission.FieldResource)
	return u
}

// SetActions sets the "actions" field.
func (u *AdminPermissionUpsert) SetActions(v []string) *AdminPermissionUpsert {
	u.Set(adminpermission.FieldActions, v)
	return u
}

// UpdateActions sets the "actions" field to the value that was provided on create.
func (u *AdminPermissionUpsert) UpdateActions() *AdminPermissionUpsert {
	u.SetExcluded(adminpermission.FieldActions)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdminPermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminPermissionUpsertOne) UpdateNewValues() *AdminPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adminpermission.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminPermission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdminPermissionUpsertOne) Ignore() *AdminPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminPermissionUpsertOne) DoNothing() *AdminPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminPermissionCreate.OnConflict
// documentation for more info.
func (u *AdminPermissionUpsertOne) Update(set func(*AdminPermissionUpsert)) *AdminPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminPermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdminPermissionUpsertOne) SetUpdatedAt(v time.Time) *AdminPermissionUpsertOne {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdminPermissionUpsertOne) UpdateUpdatedAt() *AdminPermissionUpsertOne {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdminPermissionUpsertOne) SetUserID(v int64) *AdminPermissionUpsertOne {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminPermissionUpsertOne) UpdateUserID() *AdminPermissionUpsertOne {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.UpdateUserID()
	})
}

// SetResource sets the "resource" field.
func (u *AdminPermissionUpsertOne) SetResource(v string) *AdminPermissionUpsertOne {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.SetResource(v)
	})
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *AdminPermissionUpsertOne) UpdateResource() *AdminPermissionUpsertOne {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.UpdateResource()
	})
}

// SetActions sets the "actions" field.
func (u *AdminPermissionUpsertOne) SetActions(v []string) *AdminPermissionUpsertOne {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.SetActions(v)
	})
}

// UpdateActions sets the "actions" field to the value that was provided on create.
func (u *AdminPermissionUpsertOne) UpdateActions() *AdminPermissionUpsertOne {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.UpdateActions()
	})
}

// Exec executes the query.
func (u *AdminPermissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminPermissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminPermissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdminPermissionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdminPermissionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdminPermissionCreateBulk is the builder for creating many AdminPermission entities in bulk.
type AdminPermissionCreateBulk struct {
	config
	err      error
	builders []*AdminPermissionCreate
	conflict []sql.ConflictOption
}

// Save creates the AdminPermission entities in the database.
func (_c *AdminPermissionCreateBulk) Save(ctx context.Context) ([]*AdminPermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminPermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminPermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminPermissionCreateBulk) SaveX(ctx context.Context) []*AdminPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminPermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminPermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminPermission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminPermissionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminPermissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdminPermissionUpsertBulk {
	_c.conflict = opts
	return &AdminPermissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminPermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminPermissionCreateBulk) OnConflictColumns(columns ...string) *AdminPermissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminPermissionUpsertBulk{
		create: _c,
	}
}

// AdminPermissionUpsertBulk is the builder for "upsert"-ing
// a bulk of AdminPermission nodes.
type AdminPermissionUpsertBulk struct {
	create *AdminPermissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdminPermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminPermissionUpsertBulk) UpdateNewValues() *AdminPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adminpermission.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminPermission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdminPermissionUpsertBulk) Ignore() *AdminPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminPermissionUpsertBulk) DoNothing() *AdminPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminPermissionCreateBulk.OnConflict
// documentation for more info.
func (u *AdminPermissionUpsertBulk) Update(set func(*AdminPermissionUpsert)) *AdminPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminPermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdminPermissionUpsertBulk) SetUpdatedAt(v time.Time) *AdminPermissionUpsertBulk {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdminPermissionUpsertBulk) UpdateUpdatedAt() *AdminPermissionUpsertBulk {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdminPermissionUpsertBulk) SetUserID(v int64) *AdminPermissionUpsertBulk {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminPermissionUpsertBulk) UpdateUserID() *AdminPermissionUpsertBulk {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.UpdateUserID()
	})
}

// SetResource sets the "resource" field.
func (u *AdminPermissionUpsertBulk) SetResource(v string) *AdminPermissionUpsertBulk {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.SetResource(v)
	})
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *AdminPermissionUpsertBulk) UpdateResource() *AdminPermissionUpsertBulk {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.UpdateResource()
	})
}

// SetActions sets the "actions" field.
func (u *AdminPermissionUpsertBulk) SetActions(v []string) *AdminPermissionUpsertBulk {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.SetActions(v)
	})
}

// UpdateActions sets the "actions" field to the value that was provided on create.
func (u *AdminPermissionUpsertBulk) UpdateActions() *AdminPermissionUpsertBulk {
	return u.Update(func(s *AdminPermissionUpsert) {
		s.UpdateActions()
	})
}

// Exec executes the query.
func (u *AdminPermissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdminPermissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminPermissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminPermissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
